### ISSUE TITLE
Recipe App : Kanban-board Set-up

### ISSUE THREAD

**Issue by Hamzaoutdoors** [Laylo309/Recipe-app#13]
- Link to the project [here](https://github.com/Laylo309/Recipe-app/projects/1).
- There are three members working on this project:
   - Student 1: @Laylo309 
   - Student 2: @rotimiazeez 
   - Student 3: @Hamzaoutdoors

**Comment by SajjadAhmad14** [comment]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi team, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
